name: "tfupdate"

on:
  workflow_dispatch:

jobs:
  update_terraform_versions:
    name: Update terraform versions
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: tfupdate
        uses: daisaru11/tfupdate-github-actions@v1
        with:
          tfupdate_subcommand: terraform
          tfupdate_path: "."

