name: "tfupdate"

on:
  workflow_dispatch:

jobs:
  update_terraform_versions:
    name: Update terraform versions
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: tfupdate
        uses: daisaru11/tfupdate-github-actions@v1
        with:
          tfupdate_subcommand: terraform
          tfupdate_path: "."

